### PR TITLE
Added more domains

### PR DESCRIPTION
**Pull request by anudeepND**
Source https://researchcenter.paloaltonetworks.com/2017/10/unit42-unauthorized-coin-mining-browser/
You may want to check those domains, do you think adding `www` is necessary?

### CODE REVIEW

**Comment by ZeroDot1** [comment]
@anudeepND The domains are advertising domains (popads).
The miningscripts are already blocked by the existing entries.

**Comment by anudeepND** [comment]
These domains are self hosted, please take a look at the article.

**Comment by ZeroDot1** [comment]
@anudeepND 
I can't check the addresses, I just get back that they don't exist. 
bildschirmfoto_2017-11-01_15-53-13

**Comment by ZeroDot1** [comment]
The links are all listed as malware.

**Pull request closed without merging**
